初回コミット
nanakusa27/markup_kadai_01_Gus pull request #1
Opened 2020-03-06 10:31 UTC by nanakusa27

HTMLマークアップしました
初回です。

2020-03-09 02:19 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +
`main`タグを使用しましょう。

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +        Email: kaito@quelcode.com<br>
ここは文章ではないので各行に`p`タグを使用してください。
PDFと比べて隙間が空きますが気にしなくて良いです。

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +    恵比寿ガーデンプレイス
ここも上記と同様各行に`p`タグを使用しましょう。

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +<h1>Re:QUELCODE大学の科学部参加の件</h1>
見出し部分には`section`タグを使用するようにしましょう

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +<p>千葉様<br></p>
ここの`br`タグは不要です

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +<h2>開始日</h2>
ここも`section`タグを使用しましょう。

2020-03-09 02:19 UTC, piasoratech commented on markup_kadai_01.html
> +<h2>研究の対象</h2>
ここも`section`タグを使用しましょう。

2020-03-09 15:58 UTC, nanakusa27 commented
- sectionタグを追加しました。
- mainタグを追加しました。
- 不要なbrタグを削除しました。
-pタグを追加しました。

2020-04-07 03:21 UTC, piasoratech requested changes
コメントしました！
インデントも整えるようにしてください。

2020-04-07 03:21 UTC, piasoratech commented on markup_kadai_01.html
> +<div  class="sender-column">
`address`タグをつかうのであればそちらにクラスを付与すればよいかと。

2020-04-07 03:21 UTC, piasoratech commented on markup_kadai_01.html
> +<div>
上が`address`タグならこちらも`address`のほうが良いです。

2020-04-07 03:21 UTC, piasoratech commented on markup_kadai_01.html
> +<article>
`section`タグで良いです。

2020-04-07 03:46 UTC, nanakusa27 commented
- 不要なdiv tagを無くしました。
- address tagで一つに囲みました。
- address tagにclass sender-column を付与しました。
- article tagを無くしました。
- section tagを追加しました。

2020-04-07 07:56 UTC, fjtawork commented
おっけーです！

2020-04-07 08:13 UTC, merged